---
# tasks file for mongodb

- name: Create MongoDB repo yum file
  copy:
    dest: "/etc/yum.repos.d/mongodb-org.repo"
    content: |
        [mongodb-org-4.2]
        name=MongoDB Repository
        baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
        gpgcheck=1
        enabled=1
        gpgkey=https://www.mongodb.org/static/pgp/server-4.2.asc

- name: Install the latest version of MongoDB
  dnf:
    name: mongodb-org
    state: latest

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Enable service mongod.service and ensure it is not masked
  systemd:
    name: mongod.service
    enabled: yes
    masked: no

- name: Make sure a service mongod.service is running
  systemd:
    state: started
    name: mongod.service
